EXTRACTING_DIFF = "Extracting diff between {base} and {dev}"
DIFF_STATS = "Diff: {files} files, +{added}/-{removed} lines ({loc} LOC)"
SENDING_TO_LLM = "Sending diff to Claude for analysis ({model})"
LLM_RESPONSE_RECEIVED = "Received split plan with {count} groups"
VALIDATING_PLAN = "Validating split plan"
VALIDATION_PASSED = "Plan validation passed"
LOC_SOFT_WARN = "Group '{group}' has {loc} LOC (soft limit: {limit})"
PRESENTING_PLAN = "Split plan ready for review"
CREATING_BRANCH = "Creating branch {branch} from {base}"
CREATING_MERGE_BASE = "Creating merge base {branch} from parents: {parents}"
MATERIALIZING_FILES = "Materializing {count} file(s) for group '{group}'"
COMMITTING_GROUP = "Committing group '{group}': {title}"
PUSHING_BRANCH = "Pushing {branch} to origin"
CREATING_PR = "Creating PR for group '{group}'"
PR_CREATED = "PR #{number} created: {url}"
SAVING_PLAN = "Saving plan to {path}"
PLAN_LOADED = "Loaded plan with {count} groups from {path}"
CLEANING_BRANCHES = "Cleaning up pr-split branches"
BRANCH_DELETED = "Deleted branch {branch}"
PR_CLOSED = "Closed PR #{number}"
CLEAN_COMPLETE = "Cleanup complete: {branches} branches, {prs} PRs"
FETCHING_FORK_PR = "Fetching PR #{number} from fork {fork}"
FETCHING_FORK_BRANCH = "Fetching branch {branch} from fork {fork}"
AUTHOR_PRESERVED = "Preserving author: {author}"
COUNTING_TOKENS = "Counting input tokens ({model})"
TOKEN_COUNT = "Token count: {tokens} (limit: {limit})"
DIFF_TOO_LARGE = (
    "Diff exceeds context window ({tokens} tokens > {limit} limit), switching to chunked mode"
)
CALIBRATING_CHUNKS = (
    "Overhead: {overhead} tokens, diff budget per chunk: {budget} tokens,"
    " ratio: {ratio:.4f} tokens/char"
)
CHUNKED_MODE = "Using chunked processing ({chunks} chunks, {hunks} total hunks)"
CHUNK_SENDING = "Sending chunk {index}/{total} ({hunks} hunks, ~{tokens} tokens)"
CHUNK_RECEIVED = "Chunk {index}/{total}: {new_groups} new groups, {total_groups} total"
